name: Alpha release

on:
  push:
    tags:
      - "**.**-alpha**"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 20
          cache: gradle

      - name: Generate changelog
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          writeToFile: false
          excludeTypes: ci,other,style

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          prerelease: true
          name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ github.token }}

      - name: Publish package
        run: ./gradlew publish
        env:
          GITHUB_PACKAGES_URL: https://maven.pkg.github.com/${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}